import createMiddleware from 'next-intl/middleware';
import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { routing } from './i18n/routing';

const intlMiddleware = createMiddleware(routing);

export async function middleware(request: NextRequest) {
  // Les routes API n'ont pas de locale — ne pas les passer dans next-intl
  if (request.nextUrl.pathname.startsWith('/api/')) {
    return NextResponse.next()
  }

  // First, run next-intl middleware to get the localized response
  const response = intlMiddleware(request);

  // Then, initialize Supabase using the localized response
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          // Apply cookies to the response object generated by next-intl
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  const { data: { session } } = await supabase.auth.getSession();

  // Extract path without locale
  const pathname = request.nextUrl.pathname;
  const pathWithoutLocale = pathname.replace(/^\/(fr|en)/, '') || '/';
  
  const isAuthRoute = pathWithoutLocale.startsWith('/login') || pathWithoutLocale.startsWith('/register');
  const userLocale = request.cookies.get('NEXT_LOCALE')?.value || routing.defaultLocale;

  if (isAuthRoute) {
    if (session) {
      const { data: profile } = await supabase
        .from('profiles')
        .select('is_super_admin, tenant_id, role')
        .eq('id', session.user.id)
        .single();

      if (profile?.is_super_admin) {
        return NextResponse.redirect(new URL(`/${userLocale}/admin/${session.user.id.substring(0, 5)}/dashboard`, request.url));
      }

      if (profile?.tenant_id) {
        const { data: tenant } = await supabase
          .from('tenants')
          .select('slug')
          .eq('id', profile.tenant_id)
          .single();

        if (tenant?.slug) {
          const shortId = profile.tenant_id.substring(0, 8);

          // tenant_user → rediriger vers sa première société assignée
          if (profile.role === 'tenant_user') {
            const { data: us } = await supabase
              .from('user_societes')
              .select('societe_id, societes!inner(raison_sociale)')
              .eq('user_id', session.user.id)
              .eq('is_active', true)
              .limit(1)
              .single();

            if (us?.societe_id && (us as any).societes?.raison_sociale) {
              const soc = (us as any).societes as { raison_sociale: string };
              const societeSlug = soc.raison_sociale
                .toLowerCase()
                .normalize('NFD')
                .replace(/[\u0300-\u036f]/g, '')
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-|-$/g, '');
              return NextResponse.redirect(new URL(
                `/${userLocale}/${tenant.slug}/${shortId}/${session.user.id}/${societeSlug}/${us.societe_id}/dashboard`,
                request.url
              ));
            }
          }

          // tenant_admin (ou tenant_user sans société) → tableau de bord tenant
          return NextResponse.redirect(new URL(`/${userLocale}/${tenant.slug}/${shortId}/${session.user.id}/dashboard`, request.url));
        }
      }

      // Fallback si aucun tenant ou rôle n'est trouvé
      return NextResponse.redirect(new URL(`/${userLocale}/unauthorized`, request.url));
    }
    return response;
  }

  if (!session) {
    return NextResponse.redirect(new URL(`/${userLocale}/login`, request.url));
  }

  if (pathWithoutLocale.startsWith('/admin')) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('is_super_admin')
      .eq('id', session.user.id)
      .single();

    if (!profile?.is_super_admin) {
      return NextResponse.redirect(new URL(`/${userLocale}/unauthorized`, request.url));
    }
  }

  return response;
}

export const config = {
  // Configured to match internationalized paths
  matcher: ['/', '/(fr|en)/:path*', '/((?!_next/static|_next/image|favicon.ico|api/webhooks|.*\\..*).*)']
};
