import createMiddleware from 'next-intl/middleware';
import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { routing } from './i18n/routing';

const intlMiddleware = createMiddleware(routing);

export async function middleware(request: NextRequest) {
  // First, run next-intl middleware to get the localized response
  const response = intlMiddleware(request);

  // Then, initialize Supabase using the localized response
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          // Apply cookies to the response object generated by next-intl
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  const { data: { session } } = await supabase.auth.getSession();

  // Extract path without locale
  const pathname = request.nextUrl.pathname;
  const pathWithoutLocale = pathname.replace(/^\/(fr|en)/, '') || '/';
  
  const isAuthRoute = pathWithoutLocale.startsWith('/login') || pathWithoutLocale.startsWith('/register');
  const userLocale = request.cookies.get('NEXT_LOCALE')?.value || routing.defaultLocale;

  if (isAuthRoute) {
    if (session) {
      return NextResponse.redirect(new URL(`/${userLocale}/dashboard`, request.url));
    }
    return response;
  }

  if (!session) {
    return NextResponse.redirect(new URL(`/${userLocale}/login`, request.url));
  }

  if (pathWithoutLocale.startsWith('/admin')) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('is_super_admin')
      .eq('id', session.user.id)
      .single();

    if (!profile?.is_super_admin) {
      return NextResponse.redirect(new URL(`/${userLocale}/unauthorized`, request.url));
    }
  }

  return response;
}

export const config = {
  // Configured to match internationalized paths
  matcher: ['/', '/(fr|en)/:path*', '/((?!_next/static|_next/image|favicon.ico|api/webhooks|.*\\..*).*)']
};
